/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-05 at 10:20:24 UTC 
 * Modify at your own risk.
 */

package com.threef.datastore.Entities.annotationendpoint;

/**
 * Service definition for Annotationendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AnnotationendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Annotationendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the annotationendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "annotationendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Annotationendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Annotationendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAnnotation".
   *
   * This request holds the parameters needed by the annotationendpoint server.  After setting any
   * optional parameters, call the {@link GetAnnotation#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAnnotation getAnnotation(java.lang.Long id) throws java.io.IOException {
    GetAnnotation result = new GetAnnotation(id);
    initialize(result);
    return result;
  }

  public class GetAnnotation extends AnnotationendpointRequest<com.threef.datastore.Entities.annotationendpoint.model.Annotation> {

    private static final String REST_PATH = "annotation/{id}";

    /**
     * Create a request for the method "getAnnotation".
     *
     * This request holds the parameters needed by the the annotationendpoint server.  After setting
     * any optional parameters, call the {@link GetAnnotation#execute()} method to invoke the remote
     * operation. <p> {@link GetAnnotation#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAnnotation(java.lang.Long id) {
      super(Annotationendpoint.this, "GET", REST_PATH, null, com.threef.datastore.Entities.annotationendpoint.model.Annotation.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAnnotation setAlt(java.lang.String alt) {
      return (GetAnnotation) super.setAlt(alt);
    }

    @Override
    public GetAnnotation setFields(java.lang.String fields) {
      return (GetAnnotation) super.setFields(fields);
    }

    @Override
    public GetAnnotation setKey(java.lang.String key) {
      return (GetAnnotation) super.setKey(key);
    }

    @Override
    public GetAnnotation setOauthToken(java.lang.String oauthToken) {
      return (GetAnnotation) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAnnotation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAnnotation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAnnotation setQuotaUser(java.lang.String quotaUser) {
      return (GetAnnotation) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAnnotation setUserIp(java.lang.String userIp) {
      return (GetAnnotation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAnnotation setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAnnotation set(String parameterName, Object value) {
      return (GetAnnotation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAnnotation".
   *
   * This request holds the parameters needed by the annotationendpoint server.  After setting any
   * optional parameters, call the {@link InsertAnnotation#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.threef.datastore.Entities.annotationendpoint.model.Annotation}
   * @return the request
   */
  public InsertAnnotation insertAnnotation(com.threef.datastore.Entities.annotationendpoint.model.Annotation content) throws java.io.IOException {
    InsertAnnotation result = new InsertAnnotation(content);
    initialize(result);
    return result;
  }

  public class InsertAnnotation extends AnnotationendpointRequest<com.threef.datastore.Entities.annotationendpoint.model.Annotation> {

    private static final String REST_PATH = "annotation";

    /**
     * Create a request for the method "insertAnnotation".
     *
     * This request holds the parameters needed by the the annotationendpoint server.  After setting
     * any optional parameters, call the {@link InsertAnnotation#execute()} method to invoke the
     * remote operation. <p> {@link InsertAnnotation#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.threef.datastore.Entities.annotationendpoint.model.Annotation}
     * @since 1.13
     */
    protected InsertAnnotation(com.threef.datastore.Entities.annotationendpoint.model.Annotation content) {
      super(Annotationendpoint.this, "POST", REST_PATH, content, com.threef.datastore.Entities.annotationendpoint.model.Annotation.class);
    }

    @Override
    public InsertAnnotation setAlt(java.lang.String alt) {
      return (InsertAnnotation) super.setAlt(alt);
    }

    @Override
    public InsertAnnotation setFields(java.lang.String fields) {
      return (InsertAnnotation) super.setFields(fields);
    }

    @Override
    public InsertAnnotation setKey(java.lang.String key) {
      return (InsertAnnotation) super.setKey(key);
    }

    @Override
    public InsertAnnotation setOauthToken(java.lang.String oauthToken) {
      return (InsertAnnotation) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAnnotation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAnnotation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAnnotation setQuotaUser(java.lang.String quotaUser) {
      return (InsertAnnotation) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAnnotation setUserIp(java.lang.String userIp) {
      return (InsertAnnotation) super.setUserIp(userIp);
    }

    @Override
    public InsertAnnotation set(String parameterName, Object value) {
      return (InsertAnnotation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAnnotation".
   *
   * This request holds the parameters needed by the annotationendpoint server.  After setting any
   * optional parameters, call the {@link ListAnnotation#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAnnotation listAnnotation() throws java.io.IOException {
    ListAnnotation result = new ListAnnotation();
    initialize(result);
    return result;
  }

  public class ListAnnotation extends AnnotationendpointRequest<com.threef.datastore.Entities.annotationendpoint.model.CollectionResponseAnnotation> {

    private static final String REST_PATH = "annotation";

    /**
     * Create a request for the method "listAnnotation".
     *
     * This request holds the parameters needed by the the annotationendpoint server.  After setting
     * any optional parameters, call the {@link ListAnnotation#execute()} method to invoke the remote
     * operation. <p> {@link ListAnnotation#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAnnotation() {
      super(Annotationendpoint.this, "GET", REST_PATH, null, com.threef.datastore.Entities.annotationendpoint.model.CollectionResponseAnnotation.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAnnotation setAlt(java.lang.String alt) {
      return (ListAnnotation) super.setAlt(alt);
    }

    @Override
    public ListAnnotation setFields(java.lang.String fields) {
      return (ListAnnotation) super.setFields(fields);
    }

    @Override
    public ListAnnotation setKey(java.lang.String key) {
      return (ListAnnotation) super.setKey(key);
    }

    @Override
    public ListAnnotation setOauthToken(java.lang.String oauthToken) {
      return (ListAnnotation) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAnnotation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAnnotation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAnnotation setQuotaUser(java.lang.String quotaUser) {
      return (ListAnnotation) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAnnotation setUserIp(java.lang.String userIp) {
      return (ListAnnotation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAnnotation setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAnnotation setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAnnotation set(String parameterName, Object value) {
      return (ListAnnotation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAnnotation".
   *
   * This request holds the parameters needed by the annotationendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAnnotation#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAnnotation removeAnnotation(java.lang.Long id) throws java.io.IOException {
    RemoveAnnotation result = new RemoveAnnotation(id);
    initialize(result);
    return result;
  }

  public class RemoveAnnotation extends AnnotationendpointRequest<Void> {

    private static final String REST_PATH = "annotation/{id}";

    /**
     * Create a request for the method "removeAnnotation".
     *
     * This request holds the parameters needed by the the annotationendpoint server.  After setting
     * any optional parameters, call the {@link RemoveAnnotation#execute()} method to invoke the
     * remote operation. <p> {@link RemoveAnnotation#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAnnotation(java.lang.Long id) {
      super(Annotationendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAnnotation setAlt(java.lang.String alt) {
      return (RemoveAnnotation) super.setAlt(alt);
    }

    @Override
    public RemoveAnnotation setFields(java.lang.String fields) {
      return (RemoveAnnotation) super.setFields(fields);
    }

    @Override
    public RemoveAnnotation setKey(java.lang.String key) {
      return (RemoveAnnotation) super.setKey(key);
    }

    @Override
    public RemoveAnnotation setOauthToken(java.lang.String oauthToken) {
      return (RemoveAnnotation) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAnnotation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAnnotation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAnnotation setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAnnotation) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAnnotation setUserIp(java.lang.String userIp) {
      return (RemoveAnnotation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAnnotation setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAnnotation set(String parameterName, Object value) {
      return (RemoveAnnotation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAnnotation".
   *
   * This request holds the parameters needed by the annotationendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAnnotation#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.threef.datastore.Entities.annotationendpoint.model.Annotation}
   * @return the request
   */
  public UpdateAnnotation updateAnnotation(com.threef.datastore.Entities.annotationendpoint.model.Annotation content) throws java.io.IOException {
    UpdateAnnotation result = new UpdateAnnotation(content);
    initialize(result);
    return result;
  }

  public class UpdateAnnotation extends AnnotationendpointRequest<com.threef.datastore.Entities.annotationendpoint.model.Annotation> {

    private static final String REST_PATH = "annotation";

    /**
     * Create a request for the method "updateAnnotation".
     *
     * This request holds the parameters needed by the the annotationendpoint server.  After setting
     * any optional parameters, call the {@link UpdateAnnotation#execute()} method to invoke the
     * remote operation. <p> {@link UpdateAnnotation#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.threef.datastore.Entities.annotationendpoint.model.Annotation}
     * @since 1.13
     */
    protected UpdateAnnotation(com.threef.datastore.Entities.annotationendpoint.model.Annotation content) {
      super(Annotationendpoint.this, "PUT", REST_PATH, content, com.threef.datastore.Entities.annotationendpoint.model.Annotation.class);
    }

    @Override
    public UpdateAnnotation setAlt(java.lang.String alt) {
      return (UpdateAnnotation) super.setAlt(alt);
    }

    @Override
    public UpdateAnnotation setFields(java.lang.String fields) {
      return (UpdateAnnotation) super.setFields(fields);
    }

    @Override
    public UpdateAnnotation setKey(java.lang.String key) {
      return (UpdateAnnotation) super.setKey(key);
    }

    @Override
    public UpdateAnnotation setOauthToken(java.lang.String oauthToken) {
      return (UpdateAnnotation) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAnnotation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAnnotation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAnnotation setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAnnotation) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAnnotation setUserIp(java.lang.String userIp) {
      return (UpdateAnnotation) super.setUserIp(userIp);
    }

    @Override
    public UpdateAnnotation set(String parameterName, Object value) {
      return (UpdateAnnotation) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Annotationendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Annotationendpoint}. */
    @Override
    public Annotationendpoint build() {
      return new Annotationendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AnnotationendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAnnotationendpointRequestInitializer(
        AnnotationendpointRequestInitializer annotationendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(annotationendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
